[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_MAPBOX_TOKEN = "pk.eyJ1IjoibGFodmphbC1hdmV5byIsImEiOiJjbTh0MGN2Z2EwNjc2MmtweWV2M2xhZWhoIn0.13f9IDR_jG9HfuhCsB41rQ"
  NEXT_PUBLIC_SUPABASE_URL = "https://qdxlqtkrhnwhsfihnljc.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkeGxxdGtyaG53aHNmaWhubGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzg5NDMsImV4cCI6MjA1ODc1NDk0M30.34UuqpZweEKNQ7b3xVdklLdV3iWxxoKCWsqnCyYXLZg"
